Algoritmo "soma_dois_numeros"

// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/07/2026
Var
n1, n2, soma: inteiro


Inicio
Escreval("Digite o primeiro numero:")
 Leia(n1)
Escreval("Digite o segundo numero:")
Leia(n2)
 soma <- n1 + n2
 Escreval("A soma dos numeros e:", soma)
Fimalgoritmo